In [403]:
import urllib.request

In [404]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

In [405]:
page = urllib.request.urlopen(url)

In [406]:
from bs4 import BeautifulSoup

In [407]:
soup = BeautifulSoup(page, "lxml")

In [408]:
all_tables=soup.find_all("table")

In [409]:
right_table=soup.find('table', class_='wikitable sortable')

In [410]:
A=[]
B=[]
C=[]

for row in right_table.findAll('tr'):
    cells=row.findAll('td')
    if len(cells)==3:
        A.append(cells[0].find(text=True))
        B.append(cells[1].find(text=True))
        C.append(cells[2].find(text=True))

In [411]:
import pandas as pd
df=pd.DataFrame(A,columns=['Postal code'])
df['Borough']=B
df['Neighborhood']=C
df

,Postal code,Borough,Neighborhood
0,M1A\n,Not assigned\n,Not assigned\n
1,M2A\n,Not assigned\n,Not assigned\n
2,M3A\n,North York\n,Parkwoods\n
3,M4A\n,North York\n,Victoria Village\n
4,M5A\n,Downtown Toronto\n,"Regent Park, Harbourfront\n"
...,...,...,...
175,M5Z\n,Not assigned\n,Not assigned\n
176,M6Z\n,Not assigned\n,Not assigned\n
177,M7Z\n,Not assigned\n,Not assigned\n
178,M8Z\n,Etobicoke\n,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z\n,Not assigned\n,Not assigned\n

In [412]:
df = df[(df.Borough!="Not assigned\n")]
df

,Postal code,Borough,Neighborhood
2,M3A\n,North York\n,Parkwoods\n
3,M4A\n,North York\n,Victoria Village\n
4,M5A\n,Downtown Toronto\n,"Regent Park, Harbourfront\n"
5,M6A\n,North York\n,"Lawrence Manor, Lawrence Heights\n"
6,M7A\n,Downtown Toronto\n,"Queen's Park, Ontario Provincial Government\n"
...,...,...,...
160,M8X\n,Etobicoke\n,"The Kingsway, Montgomery Road, Old Mill North\n"
165,M4Y\n,Downtown Toronto\n,Church and Wellesley\n
168,M7Y\n,East Toronto\n,"Business reply mail Processing Centre, South C..."
169,M8Y\n,Etobicoke\n,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z\n,Etobicoke\n,"Mimico NW, The Queensway West, South of Bloor,..."

In [413]:
df['Postal code'] = df['Postal code'].astype(str).str[:-1]
df['Borough'] = df['Borough'].astype(str).str[:-1]
df['Neighborhood'] = df['Neighborhood'].astype(str).str[:-1]
df

C:\Users\jfwil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jfwil\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\jfwil\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [414]:
df

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [415]:
strJoin = lambda x:",".join(x.astype(str))     
newdf = df.groupby('Postal code').agg({"Borough":strJoin,"Neighborhood":strJoin})

In [416]:
newdf

                 Borough                                       Neighborhood
Postal code
M1B          Scarborough                                     Malvern, Rouge
M1C          Scarborough             Rouge Hill, Port Union, Highland Creek
M1E          Scarborough                  Guildwood, Morningside, West Hill
M1G          Scarborough                                             Woburn
M1H          Scarborough                                          Cedarbrae
...                  ...                                                ...
M9N                 York                                             Weston
M9P            Etobicoke                                          Westmount
M9R            Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
M9V            Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
M9W            Etobicoke                Northwest, West Humber - Clairville

[103 rows x 2 columns]

In [417]:
newdf.loc[newdf.Neighborhood == 'Not assigned'].count()

Borough         0
Neighborhood    0
dtype: int64

# It can be seen that there are not "Not assigned values" to be replaced in the column Neighborhood

In [418]:
newdf.shape

(103, 2)

In [419]:
import io
import requests
url="http://cocl.us/Geospatial_data"
s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')))

In [420]:
c

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [421]:
#Latitude = c["Latitude"].astype(str)
result = pd.concat([newdf.reset_index(drop=True),c.reset_index(drop=True)], axis=1)

In [422]:
result

,Borough,Neighborhood,Postal Code,Latitude,Longitude
0,Scarborough,"Malvern, Rouge",M1B,43.806686,-79.194353
1,Scarborough,"Rouge Hill, Port Union, Highland Creek",M1C,43.784535,-79.160497
2,Scarborough,"Guildwood, Morningside, West Hill",M1E,43.763573,-79.188711
3,Scarborough,Woburn,M1G,43.770992,-79.216917
4,Scarborough,Cedarbrae,M1H,43.773136,-79.239476
...,...,...,...,...,...
98,York,Weston,M9N,43.706876,-79.518188
99,Etobicoke,Westmount,M9P,43.696319,-79.532242
100,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",M9R,43.688905,-79.554724
101,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",M9V,43.739416,-79.588437
102,Etobicoke,"Northwest, West Humber - Clairville",M9W,43.706748,-79.594054